services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network
    # restart: always

networks:
  redis-network:
    driver: bridge
